run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    # Enabled by default
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused

    # Additional recommended linters
    - gofmt
    - goimports
    - revive
    - misspell
    - unconvert
    - unparam
    - gosec
    - gocritic
    - bodyclose
    - contextcheck
    - errname
    - errorlint
    - exhaustive
    - exportloopref
    - forcetypeassert
    - gochecknoinits
    - goconst
    - goerr113
    - goprintffuncname
    - nilerr
    - nilnil
    - noctx
    - prealloc
    - predeclared
    - stylecheck
    - thelper
    - wastedassign

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable-all: true
    disable:
      - fieldalignment # too noisy for hexagonal architecture with many small structs
      - shadow

  revive:
    rules:
      - name: exported
        arguments:
          - "checkPrivateReceivers"
          - "disableStutteringCheck"

  gosec:
    excludes:
      - G404 # Use of weak random generator is ok for non-crypto use

  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - hugeParam # false positives with context
      - rangeValCopy # false positives
      - unnamedResult # not critical

  stylecheck:
    checks: ["all", "-ST1003"] # Allow underscores in package names

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-rules:
    # Exclude some linters from running on tests
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - goconst
        - goerr113
        - forcetypeassert

    # Exclude certain directories
    - path: cmd/
      linters:
        - gochecknoinits

    # Allow "magic numbers" in test files
    - path: _test\.go
      text: "mnd:"

    # Exclude some staticcheck messages
    - linters:
        - staticcheck
      text: "SA1019:" # Allow deprecated usage for now

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
